### ISSUE TITLE
Fix unittests so that unconfigured options don't fail

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#139]
## Description
As part of the process of submitting a patch to Naomi, one must check a checkbox stating "All new and existing tests have passed"

Since converting from Python 2 to Python 3, when running unittest with discover, unittest is attempting to load every module under that current directory, and failing any that fail to load. Unfortunately, a lot of the plugins (which are also modules) fail simply because they don't have prerequisites installed either under python or the larger operating system. And the osx-tts plugin forces an "Invalid Platform" import error if it detects that it is not running on OSX.

## Expected Behavior
If the user hasn't done anything in their code that causes a module to fail, then all unit tests should pass. Any modules that fail for known reasons unrelated to development should be "skipped".
```
testPluginPhraseExtraction (tests.test_brain.TestBrain) ... ok
testPriority (tests.test_brain.TestBrain)
Does Brain sort modules by priority? ... ok
testStandardPhraseExtraction (tests.test_brain.TestBrain) ... ok
testPythonImportCheck (tests.test_diagnose.TestDiagnose) ... ok
testVocabulary (tests.test_vocabcompiler.TestVocabulary) ... ok
cereproc-tts (unittest.loader._SkippedTest) ... skipped 'suds module not installed'
espeak-tts (unittest.loader._SkippedTest) ... skipped 'espeak executable not found'
festival-tts (unittest.loader._SkippedTest) ... skipped 'festival executable not found'
google-tts (unittest.loader._SkippedTest) ... skipped 'gtts module not installed'
ivona-tts (unittest.loader._SkippedTest) ... skipped 'pyvona module not installed'
mstranslator-tts (unittest.loader._SkippedTest) ... skipped 'mstranslator module not installed'
osx-tts (unittest.loader._SkippedTest) ... skipped 'Invalid platform'
pico-tts (unittest.loader._SkippedTest) ... skipped 'pico2wave executable not found'
deepspeech-stt (unittest.loader._SkippedTest) ... skipped 'deepspeech module not installed'
julius-stt (unittest.loader._SkippedTest) ... skipped 'julius executable not found'
snowboy-stt (unittest.loader._SkippedTest) ... skipped 'snowboydetect module not installed'
test_handle_method (check_email.test_check_email.TestCheckEmailPlugin) ... skipped 'Email password not available'
test_is_valid_method (check_email.test_check_email.TestCheckEmailPlugin) ... ok
test_handle_method (clock.test_clock.TestClockPlugin) ... ok
test_is_valid_method (clock.test_clock.TestClockPlugin) ... ok
test_handle_method (hackernews.test_hackernews.TestGmailPlugin) ... ok
test_is_valid_method (hackernews.test_hackernews.TestGmailPlugin) ... ok
test_handle_method (joke.test_joke.TestJokePlugin) ... ok
test_is_valid_method (joke.test_joke.TestJokePlugin) ... ok
test_handle_method (life.test_life.TestMeaningOfLifePlugin) ... ok
test_is_valid_method (life.test_life.TestMeaningOfLifePlugin) ... ok
mpdcontrol (unittest.loader._SkippedTest) ... skipped 'mpd module not installed'
test_handle_method (news.test_news.TestGmailPlugin) ... ok
test_is_valid_method (news.test_news.TestGmailPlugin) ... ok
test_get_woeid_method (weather.test_weather.TestWeatherPlugin) ... ok
test_handle_method (weather.test_weather.TestWeatherPlugin) ... ok
test_is_valid_method (weather.test_weather.TestWeatherPlugin) ... ok
----------------------------------------------------------------------
Ran 37 tests in 5.986s

ok (skipped=13)
```
## Actual Behavior
Any module/plugin that is missing dependencies or fails for known reasons will cause the unit tests to fail. This will prevent the user from being able to check box stating that all current unit tests have passed, even though there is no way they could currently get every unit test to pass without being on OSX and loading a bunch of unnecessary modules into python. In my opinion, this is an unreasonable standard.
```
testPriority (tests.test_brain.TestBrain)
Does Brain sort modules by priority? ... ok
testStandardPhraseExtraction (tests.test_brain.TestBrain) ... ok
testPythonImportCheck (tests.test_diagnose.TestDiagnose) ... ok
testVocabulary (tests.test_vocabcompiler.TestVocabulary) ... ok
cereproc-tts (unittest.loader._FailedTest) ... ERROR
espeak-tts (unittest.loader._FailedTest) ... ERROR
festival-tts (unittest.loader._FailedTest) ... ERROR
google-tts (unittest.loader._FailedTest) ... ERROR
ivona-tts (unittest.loader._FailedTest) ... ERROR
mstranslator-tts (unittest.loader._FailedTest) ... ERROR
osx-tts (unittest.loader._FailedTest) ... ERROR
pico-tts (unittest.loader._FailedTest) ... ERROR
deepspeech-stt (unittest.loader._FailedTest) ... ERROR
julius-stt (unittest.loader._FailedTest) ... ERROR
snowboy-stt (unittest.loader._FailedTest) ... ERROR
test_handle_method (check_email.test_check_email.TestCheckEmailPlugin) ... skipped 'Email password not available'
test_is_valid_method (check_email.test_check_email.TestCheckEmailPlugin) ... ok
test_handle_method (clock.test_clock.TestClockPlugin) ... ok
test_is_valid_method (clock.test_clock.TestClockPlugin) ... ok
test_handle_method (hackernews.test_hackernews.TestGmailPlugin) ... ok
test_is_valid_method (hackernews.test_hackernews.TestGmailPlugin) ... ok
test_handle_method (joke.test_joke.TestJokePlugin) ... ok
test_is_valid_method (joke.test_joke.TestJokePlugin) ... ok
test_handle_method (life.test_life.TestMeaningOfLifePlugin) ... ok
test_is_valid_method (life.test_life.TestMeaningOfLifePlugin) ... ok
mpdcontrol (unittest.loader._FailedTest) ... ERROR
test_handle_method (news.test_news.TestGmailPlugin) ... ok
test_is_valid_method (news.test_news.TestGmailPlugin) ... ok
test_get_woeid_method (weather.test_weather.TestWeatherPlugin) ... ok
test_handle_method (weather.test_weather.TestWeatherPlugin) ... ok
test_is_valid_method (weather.test_weather.TestWeatherPlugin) ... ok
----------------------------------------------------------------------
Ran 37 tests in 5.986s

FAILED (errors=12, skipped=1)
```
## Possible Fix
Instead of using "discover", we should define a specific list of tests to perform. Then we should skip any test that is going to fail simply because a prerequisite is not installed.

The following plugins currently fail if they are missing prerequisites:
Cereproc-tts:
```
~/.naomi/local/bin/pip install client suds
```
espeak-tts:
```
sudo apt install espeak
```
festival-tts:
```
sudo apt install festival
```
google-tts:
```
~/.naomi/local/bin/pip install gtts
```
ivona-tts:
```
~/.naomi/local/bin/pip install pyvona
```
mstranslator-tts:
```
~/.naomi/local/bin/pip install mstranslator
```
pico-tts:
```
sudo apt install libttspico-utils
```
deepspeech-stt
```
~/.naomi/local/bin/pip install scipy
```
pocketsphinx-stt
This requires installing the whole pocketsphinx and phonetisaurus plugin.

## Steps to Reproduce
```
~/.naomi/local/bin/python -m unittest discover -vv
```

## Context
This bug tells me that my code does not meet naomi project standards even when it does. This discourages participation in the project.

**Comment by aaronchantrill** [comment]
Just found an additional error that occurs because of the naomi/testutils.py Test_VADPlugin class. This class is an interface to be subclassed by VAD plugins to make testing easier, unfortunately the methods get picked up and are run by the unittest discover method, resulting in the following error messages:

```console
======================================================================
ERROR: test_silence (naomi.testutils.Test_VADPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Naomi/naomi/testutils.py", line 116, in test_silence
    self.assertFalse(self.plugin._voice_detected(
AttributeError: 'Test_VADPlugin' object has no attribute 'plugin'

======================================================================
ERROR: test_voice (naomi.testutils.Test_VADPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Naomi/naomi/testutils.py", line 134, in test_voice
    self.assertTrue(self.plugin._voice_detected(
AttributeError: 'Test_VADPlugin' object has no attribute 'plugin'
```

This probably isn't a brand new issue. I probably missed this originally just because there are so many error messages when unittest discover is run now.

There are a number of ways that this can be dealt with, but I think the easiest is just to add a load_tests() method to the testutils.py module which clears these tests.

**Comment by aaronchantrill** [comment]
Merged
