### ISSUE TITLE
Problems with unicode

### ISSUE THREAD

**Issue by gospodima** [NaomiProject/Naomi#146]
I have some problems with unicode in new versions of naomi

1. In local mode naomi throws an error from active_listen function if I try to send some message to naomi :
```
JASPER: My name is Naomi
JASPER: How can I be of service, Name?
DEBUG:naomi.conversation:Starting to handle conversation.
YOU: shutdown
Traceback (most recent call last):
  File "./dev/Naomi-dev/Naomi.py", line 5, in <module>
    naomi.main()
  File "/home/pi/dev/Naomi-dev/naomi/__main__.py", line 73, in main
    app.run()
  File "/home/pi/dev/Naomi-dev/naomi/application.py", line 330, in run
    self.conversation.handleForever()
  File "/home/pi/dev/Naomi-dev/naomi/conversation.py", line 49, in handleForever
    input = self.mic.listen()
  File "/home/pi/dev/Naomi-dev/naomi/local_mic.py", line 26, in listen
    return self.active_listen(timeout=3)
  File "/home/pi/dev/Naomi-dev/naomi/local_mic.py", line 20, in active_listen
    input_text = input("YOU: ")
  File "<string>", line 1, in <module>
NameError: name 'shutdown' is not defined
```

In current master & dev-branch active_listen function looks as follows:
```
def active_listen(self, timeout=3):
        input_text = input("YOU: ")
        unicodedata.normalize('NFD', input_text).encode('ascii', 'ignore')
        self.prev = input_text
        return [input_text]
``` 

But version which can be found in commit 59882f1a6d14a1de7e6c3a16fb16f62f9b99b8a8 works fine for me and doesn't throw any error:
```
def active_listen(self, timeout=3):
        input = raw_input("YOU: ").decode('utf8')
        unicodedata.normalize('NFD', input).encode('ascii', 'ignore')
        self.prev = input
        return [input]
```

2. For German language the conversation starts with:
```
JASPER: Mein name ist Naomi.
JASPER: Was kann ich fÃ¼r dich tun, Name?
```
In older versions (I tested 88127cff81d0c9691b60009bff25fcb3c1dfb90f) there is no such problem.

I also suppose that the problem can be on my side because I'm trying to run dev-branch with python 2.  I tried to run the project with python 3 but became an error:
```
INFO:pyaudio_1_0_0.pyaudioengine:Initialization of PyAudio engine finished
DEBUG:pyaudio_1_0_0.pyaudioengine:Found 10 PyAudio devices
Traceback (most recent call last):
  File "./dev/Naomi-dev/Naomi.py", line 5, in <module>
    naomi.main()
  File "/home/pi/dev/Naomi-dev/naomi/__main__.py", line 65, in main
    repopulate=p_args.repopulate
  File "/home/pi/dev/Naomi-dev/naomi/application.py", line 175, in __init__
    device_type=audioengine.DEVICE_TYPE_INPUT)]
  File "/home/pi/dev/Naomi-dev/plugins/audioengine/pyaudio-ae/pyaudioengine.py", line 53, in get_devices
    for i in range(num_devices)]
  File "/home/pi/dev/Naomi-dev/plugins/audioengine/pyaudio-ae/pyaudioengine.py", line 53, in <listcomp>
    for i in range(num_devices)]
  File "/home/pi/dev/Naomi-dev/plugins/audioengine/pyaudio-ae/pyaudioengine.py", line 94, in __init__
    super(PyAudioDevice, self).__init__(info['name'])
  File "/home/pi/dev/Naomi-dev/naomi/audioengine.py", line 46, in __init__
    self._slug = slugify.slugify(name)
  File "/usr/local/lib/python3.5/dist-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
```
Did I install incorrect version of slugify-package?

**Comment by redragonx** [comment]
As a big push for supporting Python 3, we no longer support python 2 since it's near end of life. See #129  and #90 

The master branch is still supported in python 2, our naomi-dev branch switched to Python 3. 

Let me know if python3 works for you. You might have to reinstall Naomi with the new install script.

**Comment by aaronchantrill** [comment]
@gospodima you may need to redo the import with 
`pip3 install -r python-requirements.txt`
The dev version of Naomi moved to python 3.5+ (the current version in Raspbian Stretch)
What are you running this on? Just asking out of curiosity.

**Comment by gospodima** [comment]
@aaronchantrill I am running this on Raspbian Stretch. I had some problems with pip: pip3 didn't install any packages because they were already installed but in python 2.7 folder. I hope that with `sudo python3 -m pip install -r python_requirements.txt ` I installed requirements in python 3.5 folder. And now it gives me an error that Pocketsphinx not installed. Trying now to install..

**Comment by gospodima** [comment]
Okay. I installed pocketsphinx for python3 and got the next problem: 
```
File "/home/pi/dev/Naomi-dev/plugins/tts/pico-tts/pico.py", line 46, in get_languages
    matchobj = pattern.match(output)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by redragonx** [comment]
@gospodima Can you please try our latest dev branch, @aaronchantrill pushed a fix.

**Comment by gospodima** [comment]
Now it works. Thanks!

**Comment by aaronchantrill** [comment]
Awesome. Glad to hear it.
