### ISSUE TITLE
Issue with shutdown plugin

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#172]
## Description

When you ask Naomi to shut down, there is an error caused by an outdated get_profile_var( call.

## Expected Behavior

Naomi should should just shut down:

```
$ ./Naomi.py --local
************************************************************
*                    Naomi Assistant                       *
* Made by the Naomi Community, based on the Jasper Project *
* Source code available from                               *
*    https://github.com/NaomiProject/Naomi                 *
************************************************************
JASPER: My name is Naomi.
JASPER: How can I be of service?
YOU: shutdown
JASPER: Goodbye, 
Terminated
```

## Actual Behavior

```
YOU: shutdown
ERROR:naomi.conversation:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/Naomi/naomi/conversation.py", line 57, in handleForever
    plugin.handle(text, self.mic)
  File "/home/pi/Naomi/plugins/speechhandler/shutdownplugin/shutdown.py", line 23, in handle
    name = profile.get_profile_var(self.profile,['first_name'],'')
TypeError: get_profile_var() takes from 1 to 2 positional arguments but 3 were given
JASPER: I'm sorry. I had some trouble with that operation. Please try again later.
```

## Possible Fix

Just change the line 
`name = profile.get_profile_var(self.profile,['first_name'],'')`
to
`name = profile.get_profile_var(['first_name'],'')`

## Steps to Reproduce

1. Install Naomi
2. Ask Naomi to shut down

## Context

I'm just trying to get Naomi to shut down gracefully rather than having to use a kill -15 (ctrl-C) signal

## Your Environment

* Version used: naomi-dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Python 3.5.3
* Server type and version: Raspberry Pi 3B+
* Operating System and version: Raspbian Stretch

**Comment by aaronchantrill** [comment]
Resolved with PR #186 Bug fix for shutdown plugin
