### ISSUE TITLE
Non-UTF-8 locale's crash Naomi

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#190]
## Description

Users who set their default system locale to something that uses an ISO-8859-1 character set get a bunch of errors almost immediately:
```
~/naomi-dev $ python Naomi.py 
Traceback (most recent call last):
  File "Naomi.py", line 3, in <module>
    import naomi
  File "/home/pi/naomi-dev/naomi/__init__.py", line 2, in <module>
    from .__main__ import main
  File "/home/pi/naomi-dev/naomi/__main__.py", line 6, in <module>
    from . import application
  File "/home/pi/naomi-dev/naomi/application.py", line 6, in <module>
    from . import commandline
  File "/home/pi/naomi-dev/naomi/commandline.py", line 26
SyntaxError: Non-ASCII character '\xc3' in file /home/pi/naomi-dev/naomi/commandline.py on line 26, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
pi@raspberrypi:~/naomi-dev $
```
This behavior is not currently documented, and the user gets no warning. A new user has no idea where to look for a solution, and may decide that Naomi is simply broken (especially after several hours of trying to follow instructions for installing a speech to text engine). This is less an issue for english speakers, who will probably be able to get Naomi started before encountering any unicode, but international users with extended character sets will have problems immediately.

## Expected Behavior

Naomi should just start, and you should be able to start conversing about the time and weather and whatnot.

## Actual Behavior

The user receives a cryptic and scary looking error message.

## Possible Fix

We should be able to query the character set as soon as Naomi starts up and warn the user that they may have problems before everything blows up.
`sys.getfilesystemencoding()`
perhaps?

## Steps to Reproduce

1. Install Raspbian on a Raspberry Pi
2. Set the default locale to something that uses a non-UTF-8 character set
3. Install Naomi
4. Attempt to run Naomi

## Context

Two users in the last couple of months have reported experiencing this issue.

## Your Environment

* Version used: naomi-dev
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Python 3.5.3
* Server type and version: Raspberry Pi 3B+
* Operating System and version: Raspbian Stretch
* Link to your project:

**Comment by aaronchantrill** [comment]
I think @AustinCasteel fixed this. I just tested on a Buster system configured with the default locale set to en_US ISO-8859-1 and didn't get any complaints. Can we close this?

**Comment by aaronchantrill** [comment]
This issue is fixed, both because Sekhar03 added a nice check and warning message in pull request #190 and because Raspbian OS really pushes you to use UTF-8 character sets (getting a non-UTF-8 character for testing required that I run `sudo localedef -i en_US -f ISO-8859-1 en_US` then `sudo update-locale LANG=en_US.iso88591` and finally `export LC_ALL=""` before I could actually generate the warning, however this might still be useful when run on non-Debian based operating systems. Thank you, Sekhar03.
