### ISSUE TITLE
TestCase pocketsphinx fails

### ISSUE THREAD

**Issue by andweber** [NaomiProject/Naomi#2]
when I run the testcases locally 

`coverage run ./setup.py test`

the following cases fail:

`testTranscribe (pocketsphinx-stt.tests.test_sphinxplugin.TestPocketsphinxSTTPlugin) ... No handlers could be found for logger "pocketsphinx-stt.sphinxplugin"
ERROR
testTranscribeJasper (pocketsphinx-stt.tests.test_sphinxplugin.TestPocketsphinxSTTPlugin) ... ERROR

ERROR: testTranscribe (pocketsphinx-stt.tests.test_sphinxplugin.TestPocketsphinxSTTPlugin)

Traceback (most recent call last):
  File "/home/andreas/Software/j2f/plugins/stt/pocketsphinx-stt/tests/test_sphinxplugin.py", line 17, in setUp
    'unittest-passive', ['JASPER'])
  File "/home/andreas/Software/j2f/jasper/testutils.py", line 42, in get_plugin_instance
    return plugin_class(*args)
  File "/home/andreas/Software/j2f/plugins/stt/pocketsphinx-stt/sphinxplugin.py", line 44, in **init**
    sphinxvocab.compile_vocabulary)
  File "/home/andreas/Software/j2f/jasper/plugin.py", line 82, in compile_vocabulary
    self.profile, compilation_func, self._vocabulary_phrases)
  File "/home/andreas/Software/j2f/jasper/vocabcompiler.py", line 156, in compile
    raise e
ValueError: FST model not specified!

ERROR: testTranscribeJasper (pocketsphinx-stt.tests.test_sphinxplugin.TestPocketsphinxSTTPlugin)
Traceback (most recent call last):
  File "/home/andreas/Software/j2f/plugins/stt/pocketsphinx-stt/tests/test_sphinxplugin.py", line 17, in setUp
    'unittest-passive', ['JASPER'])
  File "/home/andreas/Software/j2f/jasper/testutils.py", line 42, in get_plugin_instance
    return plugin_class(*args)
  File "/home/andreas/Software/j2f/plugins/stt/pocketsphinx-stt/sphinxplugin.py", line 44, in **init**
    sphinxvocab.compile_vocabulary)
  File "/home/andreas/Software/j2f/jasper/plugin.py", line 82, in compile_vocabulary
    self.profile, compilation_func, self._vocabulary_phrases)
  File "/home/andreas/Software/j2f/jasper/vocabcompiler.py", line 156, in compile
    raise e
ValueError: FST model not specified!

---

Ran 30 tests in 10.660s

FAILED (errors=2, skipped=1)`

Just as reference, I will look into this.

**Comment by chrobione** [comment]
do you have pocket sphinx installed?
sorry for the slow reply

**Comment by andweber** [comment]
yes, we already discussed this a time ago.
When I remember my investigation correctly, its a problem of the testcase design. The test case does not load my local profile - which is so far correct. Thus it fails to find an FST model. There simply is no standard FST model and no FST model is shipped with the test code.

Travis doesn't fail- because it has no pocket sphinx install and skips the test case. I'm uncertain about the right way to fix this. 
Possibility one:
- the test case looks in the profile and loads the correct fst model

Possibility two:
- we ship a test fst-model with the test code
  ??? there might be other solutions.

**Comment by TuxSeb** [comment]
Its been a while since this one was open, i'm closing it ...
