### ISSUE TITLE
audio_engine ALSA throws not a whole number of frames

### ISSUE THREAD

**Issue by jantos** [NaomiProject/Naomi#41]
The error always occurs if I try to keep the recording going during passive listening. For example saying a long sentence or saying jasper really slowly. This error does not happen when I change the audio_engine to pyaudio.

audio settings in profile.yaml
```
...
audio_engine: alsa

audio:
  input_device: hw-CARD-Headset-DEV-0
  output_device: hw-CARD-ALSA-DEV-0
  input_samplerate: 48000
```

Jasper.py --debug output when the error occurs:

```
DEBUG:alsa_1_0_0.alsaaudioengine:input stream opened on device 'hw-CARD-Headset-DEV-0' (48000 Hz, 1 channel, 16 bit)
DEBUG:jasper.mic:Started recording on device 'hw-CARD-Headset-DEV-0'
DEBUG:jasper.mic:Triggered on SNR of 15.3423190229dB
DEBUG:jasper.mic:Recording's SNR dB: 20.503474
DEBUG:jasper.mic:Recording's SNR dB: 20.682301
DEBUG:jasper.mic:Recording's SNR dB: 20.763940
DEBUG:jasper.mic:Recording's SNR dB: 20.933343
DEBUG:jasper.mic:Recording's SNR dB: 21.169174
DEBUG:jasper.mic:Recording's SNR dB: 21.306855
DEBUG:jasper.mic:Recording's SNR dB: 21.205832
DEBUG:jasper.mic:Recording's SNR dB: 20.996027
DEBUG:jasper.mic:Recording's SNR dB: 20.878649
DEBUG:jasper.mic:Recording's SNR dB: 20.861750
DEBUG:jasper.mic:Recording's SNR dB: 20.887086
DEBUG:jasper.mic:Recording's SNR dB: 20.832098
DEBUG:jasper.mic:Recording's SNR dB: 20.798086
DEBUG:jasper.mic:Recording's SNR dB: 20.776760
DEBUG:jasper.mic:Recording's SNR dB: 20.721067
DEBUG:jasper.mic:Recording's SNR dB: 20.759662
DEBUG:jasper.mic:Recording's SNR dB: 20.746816
DEBUG:jasper.mic:Recording's SNR dB: 20.781029
DEBUG:jasper.mic:Recording's SNR dB: 20.798086
DEBUG:jasper.mic:Recording's SNR dB: 20.806601
DEBUG:jasper.mic:Recording's SNR dB: 20.878649
DEBUG:jasper.mic:Recording's SNR dB: 20.916551
DEBUG:jasper.mic:Recording's SNR dB: 20.861750
DEBUG:jasper.mic:Recording's SNR dB: 20.840580
DEBUG:jasper.mic:Recording's SNR dB: 20.891301
DEBUG:jasper.mic:Recording's SNR dB: 20.746816
DEBUG:jasper.mic:Recording's SNR dB: 20.669340
DEBUG:jasper.mic:Recording's SNR dB: 20.647695
DEBUG:jasper.mic:Recording's SNR dB: 20.690930
DEBUG:jasper.mic:Recording's SNR dB: 20.712467
DEBUG:jasper.mic:Recording's SNR dB: 20.669340
DEBUG:jasper.mic:Recording's SNR dB: 20.660689
DEBUG:jasper.mic:Recording's SNR dB: 20.472571
DEBUG:jasper.mic:Recording's SNR dB: 20.405978
DEBUG:jasper.mic:Recording's SNR dB: 20.298356
DEBUG:jasper.mic:Recording's SNR dB: 20.253117
DEBUG:jasper.mic:Recording's SNR dB: 20.138977
DEBUG:jasper.mic:Recording's SNR dB: 20.125179
DEBUG:jasper.mic:Recording's SNR dB: 19.858763
DEBUG:jasper.mic:Recording's SNR dB: 19.661948
DEBUG:jasper.mic:Recorded 60 frames
DEBUG:alsa_1_0_0.alsaaudioengine:input stream closed on device 'hw-CARD-Headset-DEV-0'

Traceback (most recent call last):
  File "j2f/Jasper.py", line 5, in <module>
    jasper.main()
  File "/home/pi/j2f/jasper/__main__.py", line 55, in main
    app.run()
  File "/home/pi/j2f/jasper/application.py", line 302, in run
    self.conversation.handleForever()
  File "/home/pi/j2f/jasper/conversation.py", line 49, in handleForever
    input = self.mic.listen()
  File "/home/pi/j2f/jasper/mic.py", line 215, in listen
    self.wait_for_keyword(self._keyword)
  File "/home/pi/j2f/jasper/mic.py", line 178, in wait_for_keyword
    snr = self._snr([frame])
  File "/home/pi/j2f/jasper/mic.py", line 97, in _snr
    rms = audioop.rms(b''.join(frames), int(self._input_bits / 8))
audioop.error: not a whole number of frames



```

**Comment by AustinCasteel** [comment]
Abandoning issue due to being out of date. Make a new issue & pull request referencing this one if this needs to be reopened.
